CREATE TABLE USERS(
    id int GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR not null,
    email VARCHAR UNIQUE not null,
    age int check ( age > 0 ),
    weight int check ( weight > 0),
    height int check(height > 0),
    goal varchar not null
);