CREATE TABLE USERS(
    id int primary key GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR not null,
    email VARCHAR UNIQUE not null,
    age int check ( age > 0 ),
    weight float check ( weight > 0),
    height float check(height > 0),
    goal varchar not null,
    daily_calories float check ( daily_calories > 0),
    gender varchar default ('MALE') not null
);
