CREATE TABLE DishesIntake(
    id int primary key GENERATED by default AS IDENTITY,
    intakeId int not null,
    dishId int not null,
    FOREIGN KEY (intakeId) REFERENCES intakes(id),
    FOREIGN KEY (dishId) REFERENCES dishes(id)
);