version: '3.8'

services:
  db:
    image: postgres:15
    container_name: testtask_db
    environment:
      POSTGRES_DB: TestTaskDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: testtask_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/TestTaskDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: true
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data: